import type { Dialect } from "./index.js";

/**
 * One logical schema, two dialects. Timestamps are epoch milliseconds
 * (BIGINT / INTEGER) so behaviour is identical on SQLite and Postgres.
 */
export function schemaStatements(dialect: Dialect): string[] {
  const pk = dialect === "postgres" ? "SERIAL PRIMARY KEY" : "INTEGER PRIMARY KEY AUTOINCREMENT";
  const ts = dialect === "postgres" ? "BIGINT" : "INTEGER";

  const statements = [
    `CREATE TABLE IF NOT EXISTS users (
      id ${pk},
      email TEXT NOT NULL UNIQUE,
      name TEXT,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user',
      created_at ${ts} NOT NULL,
      last_signed_in ${ts}
    )`,
    `CREATE TABLE IF NOT EXISTS workspaces (
      id ${pk},
      tenant_key TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      created_by INTEGER NOT NULL,
      created_at ${ts} NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS workspace_members (
      id ${pk},
      workspace_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      role TEXT NOT NULL DEFAULT 'member',
      created_at ${ts} NOT NULL
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS ux_workspace_member ON workspace_members (workspace_id, user_id)`,
    `CREATE TABLE IF NOT EXISTS tasks (
      id ${pk},
      workspace_id INTEGER NOT NULL,
      created_by INTEGER NOT NULL,
      title TEXT NOT NULL,
      prompt TEXT NOT NULL,
      purpose TEXT NOT NULL,
      classification TEXT NOT NULL DEFAULT 'internal',
      status TEXT NOT NULL DEFAULT 'queued',
      selected_agents TEXT NOT NULL,
      budget_tokens INTEGER NOT NULL DEFAULT 4000,
      budget_bytes INTEGER NOT NULL DEFAULT 4096,
      created_at ${ts} NOT NULL,
      updated_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_tasks_workspace ON tasks (workspace_id, updated_at)`,
    `CREATE TABLE IF NOT EXISTS messages (
      id ${pk},
      task_id INTEGER NOT NULL,
      role TEXT NOT NULL,
      agent_name TEXT,
      content TEXT NOT NULL,
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_messages_task ON messages (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS agent_runs (
      id ${pk},
      task_id INTEGER NOT NULL,
      agent_name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'queued',
      request_id TEXT NOT NULL,
      input_digest TEXT NOT NULL,
      action_digest TEXT NOT NULL,
      decision TEXT,
      reason TEXT,
      output TEXT,
      error_code TEXT,
      started_at ${ts},
      completed_at ${ts},
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_runs_task ON agent_runs (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS approvals (
      id ${pk},
      task_id INTEGER NOT NULL,
      video_job_id INTEGER,
      action_digest TEXT NOT NULL,
      operation TEXT NOT NULL,
      grant_json TEXT,
      requested_by INTEGER NOT NULL,
      reviewed_by INTEGER,
      status TEXT NOT NULL DEFAULT 'pending',
      reason TEXT NOT NULL,
      nonce TEXT NOT NULL UNIQUE,
      expires_at ${ts} NOT NULL,
      reviewed_at ${ts},
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_approvals_task ON approvals (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS governance_nonces (
      id ${pk},
      nonce TEXT NOT NULL,
      kind TEXT NOT NULL,
      task_id INTEGER,
      created_at ${ts} NOT NULL
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS ux_nonce_kind ON governance_nonces (kind, nonce)`,
    `CREATE TABLE IF NOT EXISTS capability_leases (
      id ${pk},
      lease_id TEXT NOT NULL UNIQUE,
      request_id TEXT NOT NULL,
      action_digest TEXT NOT NULL,
      subject TEXT NOT NULL,
      tenant TEXT NOT NULL,
      task_id INTEGER NOT NULL,
      actor_user_id INTEGER NOT NULL,
      capability TEXT NOT NULL,
      destination TEXT,
      issued_at ${ts} NOT NULL,
      expires_at ${ts} NOT NULL,
      nonce TEXT NOT NULL UNIQUE,
      issuer TEXT NOT NULL,
      signature TEXT NOT NULL,
      interlock_generation INTEGER NOT NULL DEFAULT 0,
      consumed_at ${ts}
    )`,
    `CREATE INDEX IF NOT EXISTS ix_capability_lease_task ON capability_leases (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS effect_fences (
      id ${pk},
      effect_key TEXT NOT NULL UNIQUE,
      task_id INTEGER NOT NULL,
      tenant TEXT NOT NULL,
      capability TEXT NOT NULL,
      action_digest TEXT NOT NULL,
      interlock_generation INTEGER NOT NULL,
      fence_token TEXT NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE,
      provider TEXT NOT NULL,
      state TEXT NOT NULL CHECK (state IN ('READY','IN_FLIGHT','COMPLETED','PENDING_RECONCILIATION','FAILED')),
      provider_effect_id TEXT,
      response_digest TEXT,
      attempt_count INTEGER NOT NULL DEFAULT 0,
      created_at ${ts} NOT NULL,
      updated_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_effect_fences_task ON effect_fences (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS budget_reservations (
      id ${pk}, task_id INTEGER NOT NULL, grant_nonce TEXT NOT NULL UNIQUE, tokens INTEGER NOT NULL, bytes INTEGER NOT NULL, created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_budget_task ON budget_reservations (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS audit_events (
      id ${pk},
      task_id INTEGER,
      actor_user_id INTEGER,
      event_type TEXT NOT NULL,
      decision TEXT NOT NULL,
      reason TEXT NOT NULL,
      payload_digest TEXT NOT NULL,
      previous_hash TEXT NOT NULL,
      event_hash TEXT NOT NULL,
      occurred_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_audit_task ON audit_events (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS audit_chain_state (id INTEGER PRIMARY KEY, event_hash TEXT NOT NULL, updated_at ${ts} NOT NULL)`,
    `INSERT INTO audit_chain_state (id, event_hash, updated_at) VALUES (1, 'GENESIS', 0) ON CONFLICT (id) DO NOTHING`,
    `CREATE TABLE IF NOT EXISTS council_tasks (
      task_id TEXT PRIMARY KEY,
      source_task_id INTEGER,
      idempotency_key TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL CHECK (status IN ('RECEIVED','STATIC_VALIDATED','COUNCIL_QUEUED','PLANNING','VERIFYING','CRITIQUING','JUDGING','POLICY_DECIDED','SHADOW_COMPLETED','FAILED_CLOSED','CANCELLED','EXPIRED')),
      task_envelope_json TEXT NOT NULL,
      task_envelope_sha256 TEXT NOT NULL,
      policy_version TEXT NOT NULL,
      council_mode TEXT NOT NULL CHECK (council_mode = 'shadow'),
      created_at ${ts} NOT NULL,
      updated_at ${ts} NOT NULL,
      expires_at ${ts},
      error_code TEXT,
      error_message TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS ix_council_tasks_source ON council_tasks (source_task_id, created_at)`,
    `CREATE TABLE IF NOT EXISTS council_findings (
      finding_id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL REFERENCES council_tasks(task_id),
      role TEXT NOT NULL CHECK (role IN ('planner','verifier','critic','judge')),
      model_provider TEXT NOT NULL,
      model_version TEXT NOT NULL,
      prompt_template_sha256 TEXT NOT NULL,
      output_json TEXT NOT NULL,
      output_sha256 TEXT NOT NULL,
      schema_valid INTEGER NOT NULL CHECK (schema_valid = 1),
      created_at ${ts} NOT NULL,
      UNIQUE(task_id, role)
    )`,
    `CREATE INDEX IF NOT EXISTS ix_council_findings_task ON council_findings (task_id, created_at)`,
    `CREATE TABLE IF NOT EXISTS council_transitions (
      transition_id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL REFERENCES council_tasks(task_id),
      from_status TEXT,
      to_status TEXT NOT NULL,
      reason_code TEXT NOT NULL,
      actor_type TEXT NOT NULL,
      actor_id TEXT,
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_council_transitions_task ON council_transitions (task_id, created_at)`,
    `CREATE TABLE IF NOT EXISTS council_policy_decisions (
      decision_id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL UNIQUE REFERENCES council_tasks(task_id),
      hypothetical_outcome TEXT NOT NULL CHECK (hypothetical_outcome IN ('allow_limited_execution','require_human_approval','request_more_evidence','deny')),
      deterministic_rule_ids_json TEXT NOT NULL,
      judge_verdict_json TEXT NOT NULL,
      decision_sha256 TEXT NOT NULL,
      execution_authorized INTEGER NOT NULL CHECK (execution_authorized = 0),
      created_at ${ts} NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS video_jobs (
      id ${pk},
      task_id INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      brief TEXT,
      script TEXT,
      storyboard TEXT,
      provider TEXT,
      provider_job_id TEXT,
      error_message TEXT,
      started_at ${ts},
      completed_at ${ts},
      created_at ${ts} NOT NULL,
      updated_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_video_task ON video_jobs (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS artifacts (
      id ${pk},
      task_id INTEGER NOT NULL,
      video_job_id INTEGER,
      kind TEXT NOT NULL,
      storage_key TEXT NOT NULL,
      storage_url TEXT,
      content_type TEXT NOT NULL,
      byte_size INTEGER NOT NULL DEFAULT 0,
      sha256 TEXT NOT NULL,
      created_by INTEGER NOT NULL,
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_artifacts_task ON artifacts (task_id, id)`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id ${pk},
      user_id INTEGER,
      task_id INTEGER,
      tenant_key TEXT,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      channel TEXT NOT NULL,
      delivered INTEGER NOT NULL DEFAULT 0,
      created_at ${ts} NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS system_controls (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_by INTEGER,
      updated_at ${ts} NOT NULL
    )`,
    `INSERT INTO system_controls (key, value, updated_by, updated_at) VALUES ('interlock_generation', '0', NULL, 0) ON CONFLICT (key) DO NOTHING`,
    `CREATE TABLE IF NOT EXISTS sessions (id ${pk}, user_id INTEGER NOT NULL, token_hash TEXT NOT NULL UNIQUE, issued_at ${ts} NOT NULL, expires_at ${ts} NOT NULL, revoked_at ${ts})`,
    `CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions (user_id, expires_at)`,
    `CREATE TABLE IF NOT EXISTS login_attempts (
      id ${pk},
      email TEXT NOT NULL,
      ip TEXT NOT NULL,
      succeeded INTEGER NOT NULL,
      created_at ${ts} NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_login_attempts ON login_attempts (email, created_at)`,
  ];
  if (dialect === "postgres") {
    statements.push(
      `CREATE OR REPLACE FUNCTION gnw_current_tenant() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT NULLIF(current_setting('gnw.tenant_key', true), '') $$`,
      `ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE workspaces FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE tasks ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE tasks FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE messages ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE messages FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE agent_runs FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE approvals ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE approvals FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE capability_leases ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE capability_leases FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE effect_fences ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE effect_fences FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE video_jobs ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE video_jobs FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE artifacts ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE artifacts FORCE ROW LEVEL SECURITY`,
      `ALTER TABLE notifications ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE notifications FORCE ROW LEVEL SECURITY`,
      `DROP POLICY IF EXISTS gnw_workspaces_tenant ON workspaces`,
      `CREATE POLICY gnw_workspaces_tenant ON workspaces USING (tenant_key = gnw_current_tenant()) WITH CHECK (tenant_key = gnw_current_tenant())`,
      `DROP POLICY IF EXISTS gnw_tasks_tenant ON tasks`,
      `CREATE POLICY gnw_tasks_tenant ON tasks USING (EXISTS (SELECT 1 FROM workspaces w WHERE w.id = tasks.workspace_id AND w.tenant_key = gnw_current_tenant())) WITH CHECK (EXISTS (SELECT 1 FROM workspaces w WHERE w.id = tasks.workspace_id AND w.tenant_key = gnw_current_tenant()))`,
      `DROP POLICY IF EXISTS gnw_messages_tenant ON messages`,
      `CREATE POLICY gnw_messages_tenant ON messages USING (EXISTS (SELECT 1 FROM tasks t WHERE t.id = messages.task_id)) WITH CHECK (EXISTS (SELECT 1 FROM tasks t WHERE t.id = messages.task_id))`,
      `DROP POLICY IF EXISTS gnw_agent_runs_tenant ON agent_runs`,
      `CREATE POLICY gnw_agent_runs_tenant ON agent_runs USING (EXISTS (SELECT 1 FROM tasks t WHERE t.id = agent_runs.task_id)) WITH CHECK (EXISTS (SELECT 1 FROM tasks t WHERE t.id = agent_runs.task_id))`,
      `DROP POLICY IF EXISTS gnw_approvals_tenant ON approvals`,
      `CREATE POLICY gnw_approvals_tenant ON approvals USING (EXISTS (SELECT 1 FROM tasks t WHERE t.id = approvals.task_id)) WITH CHECK (EXISTS (SELECT 1 FROM tasks t WHERE t.id = approvals.task_id))`,
      `DROP POLICY IF EXISTS gnw_leases_tenant ON capability_leases`,
      `CREATE POLICY gnw_leases_tenant ON capability_leases USING (tenant = gnw_current_tenant()) WITH CHECK (tenant = gnw_current_tenant())`,
      `DROP POLICY IF EXISTS gnw_effect_fences_tenant ON effect_fences`,
      `CREATE POLICY gnw_effect_fences_tenant ON effect_fences USING (tenant = gnw_current_tenant()) WITH CHECK (tenant = gnw_current_tenant())`,
      `DROP POLICY IF EXISTS gnw_video_jobs_tenant ON video_jobs`,
      `CREATE POLICY gnw_video_jobs_tenant ON video_jobs USING (EXISTS (SELECT 1 FROM tasks t WHERE t.id = video_jobs.task_id)) WITH CHECK (EXISTS (SELECT 1 FROM tasks t WHERE t.id = video_jobs.task_id))`,
      `DROP POLICY IF EXISTS gnw_artifacts_tenant ON artifacts`,
      `CREATE POLICY gnw_artifacts_tenant ON artifacts USING (EXISTS (SELECT 1 FROM tasks t WHERE t.id = artifacts.task_id)) WITH CHECK (EXISTS (SELECT 1 FROM tasks t WHERE t.id = artifacts.task_id))`,
      `DROP POLICY IF EXISTS gnw_notifications_tenant ON notifications`,
      `CREATE POLICY gnw_notifications_tenant ON notifications USING (tenant_key = gnw_current_tenant()) WITH CHECK (tenant_key = gnw_current_tenant())`,
    );
  }
  return statements;
}
